title: "GO::DH"
description: "Information portal for Global Outlook Digital Humanities"
sourcecode: "https://github.com/gchauras/much-worse-jekyll-theme"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: ""     # the base hostname & protocol for your site
baseurl: "/main"                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
highlighter: rouge


# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light
