title: "GO::DH"
description: "Information portal for Global Outlook Digital Humanities"
sourcecode: "https://github.com/gchauras/much-worse-jekyll-theme"


url: ""     # the base hostname & protocol for your site
baseurl: "/main"                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
highlighter: rouge


